export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen">
      DASHBOARD HEADER
      {children}
    </main>
   
  );
}