import { Container, Header } from '@/shared/components/shared';
import { Suspense } from 'react';

export const metadata = {
  title: 'PIZZAHUB | Панель администратора',
  description: 'Generated by create next app',
};

export default async function DashboardLayout({children}: {children: React.ReactNode}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
          <Header hasCart={false} hasSearch={false} className="px-4 md:px-8 lg:px-12 border-b-gray-200" />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}