import { Container, Header } from '@/shared/components/shared';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default async function CheckoutLayout({children}: {children: React.ReactNode}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header hasCart={false} hasSearch={false} className="border-b-gray-200" />
            {children}
      </Container>
    </main>
  );
}
